### ISSUE TITLE
Update NDB profile VM builder

### ISSUE THREAD

**Issue by jacobbmay** [defenseunicorns/delivery-nutanix-image-builder#9]
The provile VM image builder should be updated with the following:

- Install postgres using unzip/source method, not package manager. NDB doesn't support postgres patching when installed via a package manager
- Update to postgres 15.x
- Add dependencies needed to support creating an HA profile in NDB. Requirements are mentioned in a [note on this page](https://portal.nutanix.com/page/documents/details?targetId=Nutanix-NDB-PostgreSQL-Database-Management-Guide-v2_6:top-software-profile-postgresql-create-t.html)

**Comment by JoeHCQ1** [comment]
I believe this is done per @jacobbmay
